### ISSUE TITLE
Windows file paths are not getting converted Unix file paths.

### ISSUE THREAD

**Issue by petahbred** [spenczar/lektor-s3#10]
![ss](https://cloud.githubusercontent.com/assets/1300226/17824315/0812fb08-6616-11e6-9b3f-3e77874afaed.png)

Amazon s3 bucket:
![ss2](https://cloud.githubusercontent.com/assets/1300226/17824334/2d8ba93e-6616-11e6-9e4c-1aa98e84349c.png)

**Comment by spenczar** [comment]
Thanks for the bug report! I have a revision incoming to fix this.

**Comment by spenczar** [comment]
Should be resolved in version 0.3.1. Please try the latest version and let me know if it works for you.
