### ISSUE TITLE
Cloudfront no invalidating 

### ISSUE THREAD

**Issue by nunojsferreira** [spenczar/lektor-s3#17]
Hello,

I am having problems invalidating the cloudfront cache.

My setup looks like this:

https://gist.github.com/nunojsferreira/002abd532490917dd9278b1b396847ed

I can't see any errors on logs and deploy seems to run with success.

Am I missing something?

Thanks,
Nuno

**Comment by nunojsferreira** [comment]
UPDATE: I think the invalidation is made but its not reported in the web console. I have no log or any evidence of the invalidation? Is this normal behaviour?

**Comment by spenczar** [comment]
This sounds like a problem with cloudfront, or perhaps your AWS setup. I'm not sure I'll be able to help here - you might have more luck asking for help from the AWS support people.
