### ISSUE TITLE
Publish 0.5

### ISSUE THREAD

**Issue by nixjdm** [spenczar/lektor-s3#19]
The error
```
import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
```
comes up when running with python 3 on version 0.4, but was fixed in a more recent commit. Could we have another release published? For my site I've currently using master via a git submodule instead of simply listing 0.5 in my project file. It seems to work fine.

I haven't thoroughly tested this repo, so I'm not sure if it's otherwise ready. My use case is basic.

**Comment by nixjdm** [comment]
actually it's looking a bit pre-mature, [as tests failed](https://github.com/spenczar/lektor-s3/pull/18) Perhaps after that's resolved?

**Comment by spenczar** [comment]
Right, now that tests are fixed, I'll get to this. Sorry for the sluggishness.

**Comment by nixjdm** [comment]
Thanks!

**Comment by spenczar** [comment]
Done: https://pypi.python.org/pypi/lektor-s3/0.5.0

Thanks for bearing with me!
