### ISSUE TITLE
public read permissions not set

### ISSUE THREAD

**Issue by krosaen** [spenczar/lektor-s3#5]
Is it just me or are the files not uploaded with public read permissions?

```
extra_args={'ACL': 'public-read'}
```

may do the trick (per [docs](http://boto3.readthedocs.org/en/latest/reference/customizations/s3.html#ref-s3transfer-usage))?

In the meantime, I manually updated the permissions after deploying.

**Comment by spenczar** [comment]
The readme mentions briefly that it expects the bucket to be set up with correct permissions ahead of time. This includes [setting the bucket policy](http://docs.aws.amazon.com/gettingstarted/latest/swh/getting-started-configure-bucket.html) to allow reads on all objects.

I don't want lektor-s3 to get in the business of managing S3 buckets and their configuration, so I'll make the readme a little louder on this topic. Does that sound fair, @krosaen?

**Comment by krosaen** [comment]
Yes, completely fair, thanks for the heads up, and sorry for the failure-to-RTFM bug report :)
